language: node_js
node_js:
    - "6"
script:
    - npm run dist
notifications:
    email: false
deploy:
    provider: script
    script: npm run push-dist
    skip_cleanup: true
    on:
      branch: master
